/** 가짜 검색 결과 데이터 타입 */
type DummyData = {
  airline: string;
  flightId: string;
  scheduleDateTime: string;
  estimatedDateTime: string;
  airport: string;
  gatenumber?: string;
  carousel?: string;
  exitnumber?: string;
  codeshare: "Master" | "Slave";
  masterflightid?: string;
  remark: "도착" | "결항" | "지연" | "회항" | "착륙" | null;
  airportCode: string;
  terminalid: string;
};

/** 가짜 검색 결과 데이터 */
const DUMMY_DATA: DummyData[] = [
  {
    airline: "대한항공",
    flightId: "KE094",
    scheduleDateTime: "202407231740",
    estimatedDateTime: "202407231736",
    airport: "워싱턴",
    gatenumber: "255",
    carousel: "12",
    exitnumber: "B",
    codeshare: "Master",
    masterflightid: "",
    remark: null,
    airportCode: "IAD",
    terminalid: "P03",
  },
  {
    airline: "대한항공",
    flightId: "KE188",
    scheduleDateTime: "202407222355",
    estimatedDateTime: "202407230010",
    airport: "타이베이",
    gatenumber: "232",
    carousel: "7",
    exitnumber: "A",
    codeshare: "Master",
    masterflightid: "",
    remark: "도착",
    airportCode: "TPE",
    terminalid: "P03",
  },
  {
    airline: "중화항공",
    flightId: "CI9066",
    scheduleDateTime: "202407222355",
    estimatedDateTime: "202407230010",
    airport: "타이베이",
    gatenumber: "232",
    carousel: "7",
    exitnumber: "A",
    codeshare: "Slave",
    masterflightid: "KE188",
    remark: "도착",
    airportCode: "TPE",
    terminalid: "P03",
  },
  {
    airline: "델타항공",
    flightId: "DL7778",
    scheduleDateTime: "202407222355",
    estimatedDateTime: "202407230010",
    airport: "타이베이",
    gatenumber: "232",
    carousel: "7",
    exitnumber: "A",
    codeshare: "Slave",
    masterflightid: "KE188",
    remark: "도착",
    airportCode: "TPE",
    terminalid: "P03",
  },
  {
    airline: "대한항공",
    flightId: "KE714Y",
    scheduleDateTime: "202407230005",
    estimatedDateTime: "202407230015",
    airport: "도쿄/나리타",
    gatenumber: "251",
    carousel: "10",
    exitnumber: "A",
    codeshare: "Master",
    masterflightid: "",
    remark: "도착",
    airportCode: "NRT",
    terminalid: "P03",
  },
  {
    airline: "일본항공",
    flightId: "JL5253Y",
    scheduleDateTime: "202407230005",
    estimatedDateTime: "202407230015",
    airport: "도쿄/나리타",
    gatenumber: "251",
    carousel: "10",
    exitnumber: "A",
    codeshare: "Slave",
    masterflightid: "KE714Y",
    remark: "도착",
    airportCode: "NRT",
    terminalid: "P03",
  },
  {
    airline: "에어서울",
    flightId: "RS704Y",
    scheduleDateTime: "202407230020",
    estimatedDateTime: "202407230013",
    airport: "도쿄/나리타",
    gatenumber: "27",
    carousel: "3",
    exitnumber: "B",
    codeshare: "Master",
    masterflightid: "",
    remark: "도착",
    airportCode: "NRT",
    terminalid: "P01",
  },
  {
    airline: "중국동방항공",
    flightId: "MU2003",
    scheduleDateTime: "202407230005",
    estimatedDateTime: "202407230017",
    airport: "쿤밍",
    gatenumber: "115",
    carousel: "11",
    exitnumber: "B",
    codeshare: "Master",
    masterflightid: "",
    remark: "도착",
    airportCode: "KMG",
    terminalid: "P02",
  },
  {
    airline: "대한항공",
    flightId: "KE5856",
    scheduleDateTime: "202407230005",
    estimatedDateTime: "202407230017",
    airport: "쿤밍",
    gatenumber: "115",
    carousel: "11",
    exitnumber: "B",
    codeshare: "Slave",
    masterflightid: "MU2003",
    remark: "도착",
    airportCode: "KMG",
    terminalid: "P02",
  },
  {
    airline: "비엣젯항공",
    flightId: "VJ838Y",
    scheduleDateTime: "202407230005",
    estimatedDateTime: "202407230018",
    airport: "나트랑",
    gatenumber: "113",
    carousel: "10",
    exitnumber: "B",
    codeshare: "Master",
    masterflightid: "",
    remark: "도착",
    airportCode: "CXR",
    terminalid: "P02",
  },
  {
    airline: "비엣젯항공",
    flightId: "VJ974Y",
    scheduleDateTime: "202407230010",
    estimatedDateTime: "202407230021",
    airport: "푸꾸옥",
    gatenumber: "109",
    carousel: "7",
    exitnumber: "B",
    codeshare: "Master",
    masterflightid: "",
    remark: "도착",
    airportCode: "PQC",
    terminalid: "P02",
  },
  {
    airline: "대한항공",
    flightId: "KE854",
    scheduleDateTime: "202407230045",
    estimatedDateTime: "202407230032",
    airport: "베이징/서우두",
    gatenumber: "252",
    carousel: "6",
    exitnumber: "A",
    codeshare: "Master",
    masterflightid: "",
    remark: "도착",
    airportCode: "PEK",
    terminalid: "P03",
  },
];

export { DUMMY_DATA };
