export const terminal1: string[] = [
  "베트남항공",
  "비엣젯항공",
  "상하이항공",
  "세부퍼시픽항공",
  "스쿠트 항공",
  "에어서울",
  "에어아시아엑스",
  "이스타항공",
  "제주항공",
  "중국남방항공",
  "중국동방항공",
  "춘추항공",
  "타이에어아시아엑스",
  "티웨이항공",
  "피치항공",
  "홍콩익스프레스",
  "라오항공",
  "로얄브루나이항공",
  "루프트한자 독일항공",
  "말레이시아 항공",
  "몽골항공",
  "미얀마국제항공",
  "바틱 에어 말레이시아",
  "사우디아항공",
  "사천항공",
  "산동항공",
  "스위스 국제항공",
  "스카이 앙코르 항공",
  "심천항공",
  "싱가포르항공",
  "아메리칸항공",
  "아시아나항공",
  "에미레이트항공",
  "에바항공",
  "에어 아스타나",
  "에어로 몽골리아",
  "에어마카오",
  "에어부산",
  "에어인디아 리미티드",
  "에어재팬",
  "에어프레미아",
  "에티오피아항공",
  "에티하드 항공",
  "우즈베키스탄항공",
  "유나이티드항공",
  "일본항공",
  "젯스타",
  "중국국제항공",
  "집에어",
  "천진항공",
  "카타르항공",
  "캐나다항공",
  "캐세이퍼시픽항공",
  "콴타스항공",
  "타이거에어 타이완",
  "타이항공",
  "터키항공",
  "폴란드항공",
  "핀에어",
  "필리핀에어아시아",
  "필리핀항공",
  "하와이안 항공",
  "홍콩항공",
];

export const terminal1LogosUrl: { [key: string]: string } = {
  베트남항공: "https://www.airport.kr/fileroot/aac/HVN_logo.png",
  비엣젯항공: "https://www.airport.kr/fileroot/aac/VJC_logo.png",
  상하이항공: "https://www.airport.kr/fileroot/aac/CSH_logo.png",
  세부퍼시픽항공: "https://www.airport.kr/fileroot/aac/CEB_logo.png",
  "스쿠트 항공": "https://www.airport.kr/fileroot/aac/20180917161356573_0.PNG",
  에어서울: "https://www.airport.kr/fileroot/aac/ASV_logo.png",
  에어아시아엑스: "https://www.airport.kr/fileroot/aac/XAX_logo.png",
  이스타항공: "https://www.airport.kr/fileroot/aac/ESR_logo.png",
  제주항공: "https://www.airport.kr/fileroot/aac/JJA_logo.png",
  중국남방항공: "https://www.airport.kr/fileroot/aac/20230629171209209_0.png",
  중국동방항공: "https://www.airport.kr/fileroot/aac/20180117174729340_0.png",
  춘추항공: "https://www.airport.kr/fileroot/aac/CQH_logo.png",
  타이에어아시아엑스: "https://www.airport.kr/fileroot/aac/TAX_logo.png",
  티웨이항공: "https://www.airport.kr/fileroot/aac/20180111165727950_0.png",
  피치항공: "https://www.airport.kr/fileroot/aac/APJ_logo.png",
  홍콩익스프레스: "https://www.airport.kr/fileroot/aac/20230525162944954_0.jpg",
  라오항공: "https://www.airport.kr/fileroot/aac/LAO_logo.png",
  로얄브루나이항공:
    "https://www.airport.kr/fileroot/aac/2018072410373275_0.png",
  "루프트한자 독일항공":
    "https://www.airport.kr/fileroot/aac/20181113144932967_0.png",
  "말레이시아 항공": "https://www.airport.kr/fileroot/aac/MAS_logo.png",
  몽골항공: "https://www.airport.kr/fileroot/aac/MGL_logo.png",
  미얀마국제항공: "https://www.airport.kr/fileroot/aac/20191202174007161_0.jpg",
  "바틱 에어 말레이시아":
    "https://www.airport.kr/fileroot/aac/20230703101655682_0.png",
  사우디아항공: "https://www.airport.kr/fileroot/aac/20220818175305340_0.jpg",
  사천항공: "https://www.airport.kr/fileroot/aac/CSC_logo.png",
  산동항공: "https://www.airport.kr/fileroot/aac/CDG_logo.png",
  "스위스 국제항공":
    "https://www.airport.kr/fileroot/aac/20240507164621678_0.png",
  "스카이 앙코르 항공": "https://www.airport.kr/fileroot/aac/SWM_logo.png",
  심천항공: "https://www.airport.kr/fileroot/aac/CSZ_logo.png",
  싱가포르항공: "https://www.airport.kr/fileroot/aac/SIA_logo.png",
  아메리칸항공: "https://www.airport.kr/fileroot/aac/20200422171205914_0.png",
  아시아나항공: "https://www.airport.kr/fileroot/aac/20180904113100184_0.png",
  에미레이트항공: "https://www.airport.kr/fileroot/aac/20190513135203281_0.png",
  에바항공: "https://www.airport.kr/fileroot/aac/20180123142834738_0.png",
  "에어 아스타나": "https://www.airport.kr/fileroot/aac/KZR_logo.png",
  "에어로 몽골리아":
    "https://www.airport.kr/fileroot/aac/20230707085147444_0.png",
  에어마카오: "https://www.airport.kr/fileroot/aac/AMU_logo.png",
  에어부산: "https://www.airport.kr/fileroot/aac/20191106164335121_0.png",
  "에어인디아 리미티드":
    "https://www.airport.kr/fileroot/aac/20231221143114501_0.png",
  에어재팬: "https://www.airport.kr/fileroot/aac/20240202142257821_0.gif",
  에어프레미아: "https://www.airport.kr/fileroot/aac/20220315173034633_0.png",
  에티오피아항공: "https://www.airport.kr/fileroot/aac/ETH_logo.png",
  "에티하드 항공": "https://www.airport.kr/fileroot/aac/ETD_logo.png",
  우즈베키스탄항공: "https://www.airport.kr/fileroot/aac/UZB_logo.png",
  유나이티드항공: "https://www.airport.kr/fileroot/aac/UAL_logo.png",
  일본항공: "https://www.airport.kr/fileroot/aac/JAL_logo.png",
  젯스타: "https://www.airport.kr/fileroot/aac/20191206111455234_0.png",
  중국국제항공: "https://www.airport.kr/fileroot/aac/CCA_logo.png",
  집에어: "https://www.airport.kr/fileroot/aac/20200922175051556_0.png",
  천진항공: "https://www.airport.kr/fileroot/aac/GCR_logo.png",
  카타르항공: "https://www.airport.kr/fileroot/aac/QTR_logo.png",
  캐나다항공: "https://www.airport.kr/fileroot/aac/ACA_logo.png",
  캐세이퍼시픽항공: "https://www.airport.kr/fileroot/aac/CPA_logo.png",
  콴타스항공: "https://www.airport.kr/fileroot/aac/QFA_logo.png",
  "타이거에어 타이완":
    "https://www.airport.kr/fileroot/aac/20191211172259144_0.png",
  타이항공: "https://www.airport.kr/fileroot/aac/THA_logo.png",
  터키항공: "https://www.airport.kr/fileroot/aac/THY_logo.png",
  폴란드항공: "https://www.airport.kr/fileroot/aac/LOT_logo.png",
  핀에어: "https://www.airport.kr/fileroot/aac/FIN_logo.png",
  필리핀에어아시아:
    "https://www.airport.kr/fileroot/aac/20180118132418635_0.png",
  필리핀항공: "https://www.airport.kr/fileroot/aac/PAL_logo.png",
  "하와이안 항공": "https://www.airport.kr/fileroot/aac/HAL_logo.png",
  홍콩항공: "https://www.airport.kr/fileroot/aac/CRK_logo.png",
};

export const terminal2: string[] = [
  "KLM네덜란드항공",
  "가루다인도네시아",
  "대한항공",
  "델타항공",
  "샤먼항공",
  "에어 프랑스",
  "중화항공",
  "진에어",
];

export const terminal2LogosUrl: { [key: string]: string } = {
  KLM네덜란드항공: "https://www.airport.kr/fileroot/aac/KLM_logo.png",
  가루다인도네시아: "https://www.airport.kr/fileroot/aac/GIA_logo.png",
  대한항공: "https://www.airport.kr/fileroot/aac/KAL_logo.png",
  델타항공: "https://www.airport.kr/fileroot/aac/DAL_logo.png",
  샤먼항공: "https://www.airport.kr/fileroot/aac/CXA_logo.png",
  "에어 프랑스": "https://www.airport.kr/fileroot/aac/AFR_logo.png",
  중화항공: "https://www.airport.kr/fileroot/aac/CAL_logo.png",
  진에어: "https://www.airport.kr/fileroot/aac/20180221144147723_0.png",
};
